// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qorreyyfgiztlmwubzey.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFvcnJleXlmZ2l6dGxtd3ViemV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxMzI2NzAsImV4cCI6MjA2MDcwODY3MH0.POSHqLX1v-Dry7ewEvA1mI88axzS-OWfKyjvYxtANtA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);