// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://scvpjaxthcrjphxlzjti.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNjdnBqYXh0aGNyanBoeGx6anRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0Nzk4NTIsImV4cCI6MjA2MTA1NTg1Mn0.M0DGJ5DWVqoqMaPEtc0nqcJOyfayfDxS6YFHTWcKnrE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);